spring:
  data:
    web:
      pageable:
        max-page-size: 100
        default-page-size: 20
  datasource:
    url: jdbc:postgresql://localhost:5432/spaceexplorer
    username: dev
    password: dev
  jpa:
    hibernate:
      ddl-auto: validate
  http:
    client:
      connect-timeout: 3s
      read-timeout: 5s
logging:
  level:
    org.hibernate.SQL: DEBUG